name: 'dbt_airflow_monitoring'
version: '0.1.0'

require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs" 

profile: dbt_airflow_monitoring

vars:
    dbt_airflow_monitoring:
       airflow_monitoring_start_date: cast('2023-01-01' as date)

models:
  dbt_airflow_monitoring:
    marts:
      materialized: table
    staging:
      airflow_sources:
        enabled: false
      adf_sources:
        enabled: false
      databricks_workflow_sources:
        enabled: true