name: 'dbt_dag_monitoring'
version: '0.2.0'

require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs" 

profile: dbt_dag_monitoring

models:
  dbt_dag_monitoring:
    marts:
      +materialized: table
    staging:
      +materialized: view

