name: 'dbt_dag_monitoring'
version: '0.2.0'

require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs" 

profile: dbt_dag_monitoring

vars:
  enabled_sources: ['airflow']
  dbt_dag_monitoring:
    dag_monitoring_start_date: cast('2023-01-01' as date)

models:
  dbt_dag_monitoring:
    marts:
      materialized: table
    staging:
      airflow_sources:
        enabled: true
      adf_sources:
        enabled: false
      databricks_workflow_sources:
        enabled: false
