name: 'dbt_dag_monitoring'
version: '0.2.0'

require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs" 

profile: dbt_dag_monitoring

vars:
  enabled_sources: ['airflow']
  dbt_dag_monitoring:
    dag_monitoring_start_date: cast('2023-01-01' as date)

models:
  dbt_dag_monitoring:
    marts:
      materialized: table
    staging:
      airflow_sources:
        enabled: true
      adf_sources:
        enabled: true
      databricks_workflow_sources:
        enabled: true

seeds:
    dbt_dag_monitoring:
      +database: # respective database
      +tags: integration_tests
      +schema: # respective schema

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

vars:
    enabled_sources: ['airflow'] # Possible values airflow, adf and databricks_workflow.
    dbt_dag_monitoring:
       dag_monitoring_start_date: cast('2023-01-01' as date) # edit date here
    dag_monitoring_airflow_database: # respective airflow database
    dag_monitoring_airflow_schema: # respective airflow schema
    dag_monitoring_databricks_database: # respective databricks database
    dag_monitoring_databricks_schema: # respective databricks schema
    dag_monitoring_adf_database: # respective adf database
    dag_monitoring_adf_schema: # respective adf schema
